M48
; DRILL file {KiCad (6.0.6)} date Thu Nov  3 15:56:20 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-03T15:56:20+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1181
%
G90
G05
T1
X3.6649Y-2.5546
X3.6649Y-2.6727
T2
X6.163Y-4.4425
X6.363Y-4.7425
T3
X3.7031Y-5.1378
T4
X4.0315Y-4.5079
X6.2047Y-5.1378
T0
M30
